/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSobreRouteImport } from './routes/_site.sobre'
import { Route as SiteProdutosRouteImport } from './routes/_site.produtos'
import { Route as SiteLojasRouteImport } from './routes/_site.lojas'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSobreRoute = SiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProdutosRoute = SiteProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLojasRoute = SiteLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/contato': typeof SiteContatoRoute
  '/lojas': typeof SiteLojasRoute
  '/produtos': typeof SiteProdutosRoute
  '/sobre': typeof SiteSobreRoute
}
export interface FileRoutesByTo {
  '/contato': typeof SiteContatoRoute
  '/lojas': typeof SiteLojasRoute
  '/produtos': typeof SiteProdutosRoute
  '/sobre': typeof SiteSobreRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/contato': typeof SiteContatoRoute
  '/_site/lojas': typeof SiteLojasRoute
  '/_site/produtos': typeof SiteProdutosRoute
  '/_site/sobre': typeof SiteSobreRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contato' | '/lojas' | '/produtos' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/contato' | '/lojas' | '/produtos' | '/sobre' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/contato'
    | '/_site/lojas'
    | '/_site/produtos'
    | '/_site/sobre'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sobre': {
      id: '/_site/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SiteSobreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/produtos': {
      id: '/_site/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof SiteProdutosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lojas': {
      id: '/_site/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof SiteLojasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteLojasRoute: typeof SiteLojasRoute
  SiteProdutosRoute: typeof SiteProdutosRoute
  SiteSobreRoute: typeof SiteSobreRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteLojasRoute: SiteLojasRoute,
  SiteProdutosRoute: SiteProdutosRoute,
  SiteSobreRoute: SiteSobreRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
